### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by siyuanwu99** [bowenXuu/pred_occ_planner_plus#1]
感谢关注！
这个项目是我硕士期间做的一点小小的工作，作为对于之前 RAST 工作的扩展。由于动态建图的部分还不是非常稳定，所以用真值的 OGM 地图整理了一下规划的部分。开源的版本状态机还有一些问题，我七八月份的时候修改了很多。仿真器中的地图部分也改成了支持任意点云地图的格式。如果你还对这个项目感兴趣我给你最新的版本。

**Comment by bowenXuu** [comment]
Siyuan你好，感谢你的关注，
在今年年初的时候我将你的 pred-occ-planner 部署到实机中做了一些测试实验，并与我参与的一项无人机动态避障工作进行了性能对比（那时候在找一些比较新颖的 dynamic 避障方法作为 baseline，你的这个项目让我眼前一亮），因此当时上传了这个所谓的“plus”版本记录一下我的一些小小改动。

我目前正在做我的本科毕业设计，仍然是复杂动态环境避障的方向。如果你愿意的话，我非常乐意获取这个项目的最新版本，我相信这会对我的开发有很大帮助！

**Comment by bowenXuu** [comment]
Hi，关于这个 issue 我上周（link.bowenxu@gmail.com）发了邮件给你，如果有空的话麻烦回复我一下，谢谢。
